# GitHub Actions workflow voor een Node.js project
# Voert een clean install uit, bouwt de code en draait tests op meerdere Node-versies

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Gebruik alleen stabiele versies

    steps:
    - name: Haal repository op
      uses: actions/checkout@v4

    - name: Installeer Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: 'npm'

    - name: Installeer afhankelijkheden
      run: npm ci

    - name: Bouw de applicatie (indien van toepassing)
      run: npm run build --if-present

    - name: Voer tests uit
      run: npm test
