name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Fix: Check of package-lock.json bestaat, zo niet, voer npm install uit
    - name: Controleer of package-lock.json bestaat
      run: |
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json ontbreekt, npm install uitvoeren..."
          npm install
        fi

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
